// 자동 생성 — scripts 기반. 원본: 주간보고록.xlsx (2026년 2~7월, 3,547행)
// MKT·플랫폼팀은 그로스팀 개편 이슈로 제외. MD1/MD2 는 브랜드팀으로 통합 반영.
// 이메일은 임시 placeholder — 실제 계정으로 교체 필요.

export type MetricKind = "auto" | "monthly" | "weekly" | "project";
export type MetricUnit = "currency" | "percent" | "count";

export interface Metric {
  id: string;
  name: string;
  scopes?: string[];
  kind: MetricKind;
  unit: MetricUnit;
  /** 직전 4주 실적 (W1~W4) — 자동 집계 지표의 시트 동기화분 */
  weeks?: (number | null)[];
  /** 담당 정리 등 비고 */
  note?: string;
  /** 상반기(7월) 마지막 값 — 하반기 시작 기준선 */
  baseline: number | null;
  /** 이번 주 입력값 */
  value?: number | null;
}

export interface Person {
  name: string;
  position?: string;
  email: string;
  division: string;
  team: string;
  isLeader?: boolean;
  /** 담당 범위 */
  scope?: string;
  metrics: Metric[];
}

export const DIVISIONS = ["CEO본부", "COO본부", "CPO본부"];

export const TEAM_ORDER: Record<string, string[]> = {
  "CEO본부": ["전략기획팀", "해외팀"],
  "COO본부": ["경영지원팀", "브랜드팀", "CS팀"],
  "CPO본부": ["상품기획팀", "디자인팀", "패션팀", "개발팀"],
};

export const PEOPLE: Person[] = [
  {
    name: "이동훈",
    email: "donghoon@biteme.co.kr",
    division: "CEO본부",
    team: "전략기획팀",
    metrics: [
      {
        id: "donghoon-1",
        name: "로직 오류 발생율",
        kind: "weekly",
        unit: "percent",
        baseline: 0.8,
      },
      {
        id: "donghoon-2",
        name: "데이터 누락 발생율",
        kind: "weekly",
        unit: "percent",
        baseline: 10,
      },
      {
        id: "donghoon-3",
        name: "리포트 자동화율",
        kind: "weekly",
        unit: "percent",
        baseline: 100,
      },
      {
        id: "donghoon-4",
        name: "데이터 이슈 대응 SLA 준수율",
        kind: "weekly",
        unit: "percent",
        baseline: 100,
      },
      {
        id: "donghoon-5",
        name: "긴급 분석 요청 SLA 준수율",
        kind: "weekly",
        unit: "percent",
        baseline: 100,
      },
    ],
  },
  {
    name: "주수현",
    email: "suhyun@biteme.co.kr",
    division: "CEO본부",
    team: "해외팀",
    metrics: [
      {
        id: "suhyun-1",
        name: "글로벌몰 객단가",
        kind: "auto",
        unit: "currency",
        baseline: 268070,
      },
      {
        id: "suhyun-2",
        name: "글로벌몰 CVR",
        kind: "weekly",
        unit: "percent",
        baseline: 22.22,
      },
      {
        id: "suhyun-3",
        name: "글로벌몰 주문건수",
        kind: "weekly",
        unit: "count",
        baseline: 20,
      },
      {
        id: "suhyun-4",
        name: "총판 나라별 누적 주문액",
        kind: "weekly",
        unit: "currency",
        baseline: 348103187,
      },
      {
        id: "suhyun-5",
        name: "총판 신제품 도입율",
        kind: "weekly",
        unit: "percent",
        baseline: 27,
      },
    ],
  },
  {
    name: "박예선",
    email: "yeseon@biteme.co.kr",
    division: "COO본부",
    team: "경영지원팀",
    metrics: [
      {
        id: "yeseon-1",
        name: "국내결산 손익계산서 일정 준수",
        kind: "monthly",
        unit: "count",
        baseline: 100,
      },
      {
        id: "yeseon-2",
        name: "사업부별 손익계산서 마감",
        kind: "monthly",
        unit: "count",
        baseline: 100,
      },
      {
        id: "yeseon-3",
        name: "월간 캐시플로우 목표편차",
        kind: "project",
        unit: "percent",
        baseline: 0,
      },
      {
        id: "yeseon-4",
        name: "단기 운영 현금 확보율",
        kind: "project",
        unit: "percent",
        baseline: 177,
      },
      {
        id: "yeseon-5",
        name: "현금 재고자산 리스크 검토",
        kind: "project",
        unit: "count",
        baseline: 0,
      },
    ],
  },
  {
    name: "정경화",
    email: "kyunghwa@biteme.co.kr",
    division: "COO본부",
    team: "경영지원팀",
    metrics: [
      {
        id: "kyunghwa-1",
        name: "국내결산 일정 준수",
        kind: "monthly",
        unit: "count",
        baseline: 20,
      },
      {
        id: "kyunghwa-2",
        name: "일본결산 일정 준수",
        kind: "monthly",
        unit: "count",
        baseline: 10,
      },
      {
        id: "kyunghwa-3",
        name: "고정비 효율화율",
        kind: "weekly",
        unit: "percent",
        baseline: 60,
      },
      {
        id: "kyunghwa-4",
        name: "부채 해외리스크 검토",
        kind: "weekly",
        unit: "count",
        baseline: 75,
      },
      {
        id: "kyunghwa-5",
        name: "리스크 항목 개선 실행율",
        kind: "project",
        unit: "percent",
        baseline: 60,
      },
    ],
  },
  {
    name: "이지윤",
    position: "팀장",
    isLeader: true,
    email: "jiyun@biteme.co.kr",
    division: "COO본부",
    team: "브랜드팀",
    scope: "B2B · 쿠팡 · 외부채널",
    metrics: [
      {
        id: "jiyun-1",
        name: "B2B 스테디 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 504689, null],
        baseline: 504689,
        note: "유하선과 중복 → 이지윤 단독",
      },
      {
        id: "jiyun-2",
        name: "B2B 시즈널 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 1761081, null],
        baseline: 1761081,
        note: "유하선과 중복 → 이지윤 단독",
      },
      {
        id: "jiyun-3",
        name: "쿠팡 스테디 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 1274693, null],
        baseline: 1274693,
        note: "유하선과 중복 → 이지윤 단독",
      },
      {
        id: "jiyun-4",
        name: "쿠팡 시즈널 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 129965, null],
        baseline: 129965,
        note: "유하선과 중복 → 이지윤 단독",
      },
      {
        id: "jiyun-5",
        name: "그외 스테디 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 2192298, null],
        baseline: 2192298,
      },
      {
        id: "jiyun-6",
        name: "그외 시즈널 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [null, null, 4472182, null],
        baseline: 4472182,
      },
      {
        id: "jiyun-7",
        name: "B2B 신규 구매자 수",
        kind: "auto",
        unit: "count",
        weeks: [null, null, 8, null],
        baseline: 8,
        note: "유하선과 중복 → 이지윤 단독",
      },
      {
        id: "jiyun-8",
        name: "카카오 플친 구독 수",
        kind: "auto",
        unit: "count",
        weeks: [null, null, 1237, null],
        baseline: 1237,
        note: "유하선과 중복 → 이지윤 단독",
      },
    ],
  },
  {
    name: "유하선",
    email: "hasun@biteme.co.kr",
    division: "COO본부",
    team: "브랜드팀",
    scope: "자사몰 · 스마트스토어",
    metrics: [
      {
        id: "hasun-1",
        name: "스테디 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [2018169, 2988002, 1986653, 2988002],
        baseline: 2988002,
      },
      {
        id: "hasun-2",
        name: "시즈널 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [2029098, 2029098, 2755572, 2029098],
        baseline: 2029098,
      },
      {
        id: "hasun-3",
        name: "바잇미 관심고객수",
        kind: "auto",
        unit: "count",
        weeks: [149956, 149956, 152365, 149956],
        baseline: 149956,
      },
      {
        id: "hasun-4",
        name: "바잇미 단종 SKU 방출액",
        kind: "auto",
        unit: "currency",
        weeks: [null, 1188371, 1316931, 1188371],
        baseline: 1188371,
        note: "김소희와 중복 → 자사몰분은 유하선",
      },
      {
        id: "hasun-5",
        name: "바잇미 라이브 운영 횟수",
        kind: "weekly",
        unit: "count",
        weeks: [0, 1, 1, 1],
        baseline: 1,
        note: "유일한 주간 수기 입력",
      },
    ],
  },
  {
    name: "김소희",
    email: "sohee@biteme.co.kr",
    division: "COO본부",
    team: "브랜드팀",
    scope: "세컨브랜드 (SSFW · 컴피라비올리)",
    metrics: [
      {
        id: "sohee-1",
        name: "세컨브랜드 SKU 공헌이익",
        kind: "auto",
        unit: "currency",
        weeks: [618742, 1122480, 958755, 1107776],
        baseline: 1107776,
      },
      {
        id: "sohee-2",
        name: "SSFW 관심고객수",
        kind: "auto",
        unit: "count",
        weeks: [6201, 6289, 6306, 6344],
        baseline: 6344,
      },
      {
        id: "sohee-3",
        name: "컴피라비올리 관심고객수",
        kind: "auto",
        unit: "count",
        weeks: [2564, 2598, 2609, 2655],
        baseline: 2655,
      },
      {
        id: "sohee-4",
        name: "세컨브랜드 재고 방출액",
        kind: "auto",
        unit: "currency",
        weeks: [1260694, 4957707, 1851951, 2341527],
        baseline: 2341527,
      },
      {
        id: "sohee-5",
        name: "외부채널 단종 SKU 방출액",
        kind: "auto",
        unit: "currency",
        weeks: [175205, 241631, 231401, 175374],
        baseline: 175374,
      },
    ],
  },
  {
    name: "김진하",
    position: "팀장",
    isLeader: true,
    email: "jinha@biteme.co.kr",
    division: "COO본부",
    team: "CS팀",
    metrics: [
      {
        id: "jinha-1",
        name: "고객만족도",
        kind: "auto",
        unit: "percent",
        baseline: 95.3,
      },
      {
        id: "jinha-2",
        name: "1차 상담 종결율",
        kind: "auto",
        unit: "percent",
        baseline: 100,
      },
      {
        id: "jinha-3",
        name: "브랜드 리스크 관리 및 전환 향상[스테디]",
        kind: "auto",
        unit: "count",
        baseline: 4.87,
      },
      {
        id: "jinha-4",
        name: "브랜드 리스크 관리 및 전환 향상[시즈널]",
        kind: "auto",
        unit: "count",
        baseline: 4.85,
      },
      {
        id: "jinha-5",
        name: "결품 프로세스 수행율",
        kind: "weekly",
        unit: "percent",
        baseline: 100,
      },
      {
        id: "jinha-6",
        name: "채널톡 운영비 절감",
        kind: "weekly",
        unit: "currency",
        baseline: 19840022,
      },
      {
        id: "jinha-7",
        name: "cs원인 재문의율",
        kind: "project",
        unit: "percent",
        baseline: 0,
      },
      {
        id: "jinha-8",
        name: "CS 문의내용 KMS 문서화",
        kind: "project",
        unit: "count",
        baseline: 100,
      },
    ],
  },
  {
    name: "김현진",
    email: "hyunjin@biteme.co.kr",
    division: "COO본부",
    team: "CS팀",
    metrics: [
      {
        id: "hyunjin-1",
        name: "만족도 조사 안내율",
        kind: "auto",
        unit: "percent",
        baseline: 99.7,
      },
      {
        id: "hyunjin-2",
        name: "만족도 조사 결과",
        kind: "auto",
        unit: "percent",
        baseline: 96.78,
      },
      {
        id: "hyunjin-3",
        name: "생산성 향상 상담 상대점수",
        kind: "weekly",
        unit: "count",
        baseline: 2.1,
      },
    ],
  },
  {
    name: "김지현",
    email: "jihyun@biteme.co.kr",
    division: "COO본부",
    team: "CS팀",
    metrics: [
      {
        id: "jihyun-1",
        name: "만족도 조사 안내율 [지현]",
        kind: "auto",
        unit: "percent",
        baseline: 100,
      },
      {
        id: "jihyun-2",
        name: "만족도 조사 결과 [지현]",
        kind: "auto",
        unit: "percent",
        baseline: 94.73,
      },
      {
        id: "jihyun-3",
        name: "생산성 향상 상담 상대점수 [지현]",
        kind: "weekly",
        unit: "percent",
        baseline: 1,
      },
    ],
  },
  {
    name: "손유진",
    email: "yujin@biteme.co.kr",
    division: "COO본부",
    team: "CS팀",
    metrics: [],
  },
  {
    name: "박정민",
    email: "jungmin@biteme.co.kr",
    division: "COO본부",
    team: "CS팀",
    metrics: [],
  },
  {
    name: "장근혜",
    email: "geunhye@biteme.co.kr",
    division: "CPO본부",
    team: "상품기획팀",
    metrics: [
      {
        id: "geunhye-1",
        name: "식/용품 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 38.8,
      },
      {
        id: "geunhye-2",
        name: "신제품 목표일정 준수율(입고일)",
        scopes: ["브레이닝토이", "슬리커", "신발", "튜브"],
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "정예진",
    email: "yejin@biteme.co.kr",
    division: "CPO본부",
    team: "상품기획팀",
    metrics: [
      {
        id: "yejin-1",
        name: "식/용품 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 37,
      },
      {
        id: "yejin-2",
        name: "신제품 누적 공헌이익",
        scopes: ["덴타링"],
        kind: "auto",
        unit: "currency",
        baseline: 23128792,
      },
      {
        id: "yejin-3",
        name: "팀 카테고리별 마진밴드 준수율",
        scopes: ["영양제/식품", "용품"],
        kind: "weekly",
        unit: "percent",
        baseline: 44.66,
      },
      {
        id: "yejin-4",
        name: "신제품 마진밴드 준수율",
        scopes: ["덴타링"],
        kind: "weekly",
        unit: "percent",
        baseline: 36.26,
      },
      {
        id: "yejin-5",
        name: "신제품 목표일정 준수율(입고일)",
        scopes: ["꿀맛트릿"],
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "최은주",
    email: "eunju@biteme.co.kr",
    division: "CPO본부",
    team: "상품기획팀",
    metrics: [
      {
        id: "eunju-1",
        name: "장난감 출시 30일 초기 반품/교환율",
        kind: "auto",
        unit: "percent",
        baseline: null,
      },
      {
        id: "eunju-2",
        name: "신상 장난감 초기 반품교환건",
        kind: "auto",
        unit: "count",
        baseline: 0,
      },
      {
        id: "eunju-3",
        name: "장난감 품질 이슈율",
        scopes: ["점핑부기"],
        kind: "project",
        unit: "percent",
        baseline: null,
      },
      {
        id: "eunju-4",
        name: "장난감 쇼트 발생률",
        scopes: ["출시 60일 내 쇼트 발생 건수"],
        kind: "project",
        unit: "count",
        baseline: null,
      },
      {
        id: "eunju-5",
        name: "브레이닝 토끼 수급",
        kind: "project",
        unit: "count",
        baseline: 0,
      },
      {
        id: "eunju-6",
        name: "젤리곰 블링커 품질 관리",
        kind: "project",
        unit: "count",
        baseline: 0,
      },
    ],
  },
  {
    name: "김민기",
    email: "minki@biteme.co.kr",
    division: "CPO본부",
    team: "디자인팀",
    metrics: [
      {
        id: "minki-1",
        name: "신제품 누적 공헌이익",
        kind: "auto",
        unit: "currency",
        baseline: 60706011,
      },
      {
        id: "minki-2",
        name: "장난감 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.579,
      },
      {
        id: "minki-3",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "유예진",
    email: "yaejin@biteme.co.kr",
    division: "CPO본부",
    team: "디자인팀",
    metrics: [
      {
        id: "yaejin-1",
        name: "신제품 누적 공헌이익",
        kind: "auto",
        unit: "currency",
        baseline: 172518712,
      },
      {
        id: "yaejin-2",
        name: "장난감 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.446,
      },
      {
        id: "yaejin-3",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "정소현",
    email: "sohyun@biteme.co.kr",
    division: "CPO본부",
    team: "디자인팀",
    metrics: [
      {
        id: "sohyun-1",
        name: "신제품 누적 공헌이익",
        kind: "auto",
        unit: "currency",
        baseline: 47753986,
      },
      {
        id: "sohyun-2",
        name: "장난감 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.579,
      },
      {
        id: "sohyun-3",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "김민정",
    email: "minjung@biteme.co.kr",
    division: "CPO본부",
    team: "패션팀",
    metrics: [
      {
        id: "minjung-1",
        name: "패션 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.174,
      },
      {
        id: "minjung-2",
        name: "신제품 누적 공헌이익",
        kind: "auto",
        unit: "currency",
        baseline: 104277035,
      },
      {
        id: "minjung-3",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "project",
        unit: "percent",
        baseline: 0,
      },
      {
        id: "minjung-4",
        name: "출시 SKU 갯수 준수율",
        kind: "project",
        unit: "count",
        baseline: 0,
      },
    ],
  },
  {
    name: "박서희",
    email: "seohee@biteme.co.kr",
    division: "CPO본부",
    team: "패션팀",
    metrics: [
      {
        id: "seohee-1",
        name: "패션 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.144,
      },
      {
        id: "seohee-2",
        name: "신제품 누적 공헌이익",
        scopes: ["SS 산리오 쿨 슬리브리스", "SS 산리오 쿨 파우치", "산리오 쿨 슬리브리스", "산리오 쿨 파우치", "슬리브리스", "파우치"],
        kind: "auto",
        unit: "currency",
        baseline: 21794985,
      },
      {
        id: "seohee-3",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "project",
        unit: "percent",
        baseline: null,
      },
    ],
  },
  {
    name: "심소라",
    email: "sora@biteme.co.kr",
    division: "CPO본부",
    team: "패션팀",
    metrics: [
      {
        id: "sora-1",
        name: "패션 카테고리 공헌이익 기여도",
        kind: "auto",
        unit: "currency",
        baseline: 0.174,
      },
      {
        id: "sora-2",
        name: "신제품 목표일정 준수율(입고일)",
        kind: "weekly",
        unit: "percent",
        baseline: null,
      },
      {
        id: "sora-3",
        name: "출시 SKU 갯수 준수율",
        kind: "weekly",
        unit: "count",
        baseline: null,
      },
    ],
  },
  {
    name: "박인애",
    email: "inae@biteme.co.kr",
    division: "CPO본부",
    team: "개발팀",
    metrics: [
      {
        id: "inae-1",
        name: "프로젝트 종결 건수",
        kind: "weekly",
        unit: "count",
        baseline: 0,
      },
      {
        id: "inae-2",
        name: "플랫폼 유료구좌 기능 구현 건수",
        kind: "project",
        unit: "count",
        baseline: 0,
      },
    ],
  },
];
